## HASS ##
homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  customize: !include customize.yaml

http:
  api_password: !secret hass_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

## DEVICES ##
alert: !include devices/alerts.yaml
binary_sensor: !include devices/binary_sensors.yaml
climate: !include devices/climates.yaml
device_tracker: !include devices/device_trackers.yaml
envisalink: !include devices/envisalink.yaml
media_player: !include devices/media_players.yaml
notify: !include devices/notifies.yaml

## GROUPS ##
group: !include groups.yaml

## AUTOMATION ##
automation: !include automations.yaml

## ACTIVATE ##
frontend:
config:
updater:
  include_used_components: true
discovery:
  ignore:
    - netgear_router
conversation:
tts:
  platform: google
history:
logbook:
sun:
sensor:
  platform: yr
