## HASS ##
homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  customize: !include customize.yaml

http:
  api_password: !secret hass_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

## DEVICES ##
device_tracker: !include devices/device_trackers.yaml
media_player: !include devices/media_players.yaml
climate: !include devices/climates.yaml

## GROUPS ##
group: !include groups.yaml

## AUTOMATION ##
automation: !include automations.yaml

## ACTIVATE ##
frontend:
config:
updater:
  include_used_components: true
discovery:
  ignore:
    - netgear_router
conversation:
tts:
  platform: google
history:
logbook:
sun:
sensor:
  platform: yr
